title: Robin Tegg
author: Robin Tegg
email: robin@tegg.me.uk
description: >- # this means to ignore newlines until "baseurl:"
  A Java developer. Based in Leeds, England. Has interest in Software Architecture, Testing, Automation, Tooling and UI design. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.robintegg.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: robintegg
github_username:  teggr
google_analytics: UA-112481105-1
linkedin_username: robintegg

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# seo-plugin
twitter:
  username: robintegg

# menu
header_pages:
  - books/index.html
  - podcasts/index.html
  - tags/index.html

# collections
collections:
  books:
    output: true
    sort_by: title
  podcasts:
    output: true
    sort_by: title